server:
  port: 8888
spring:
  application:
    name: gateway
  profiles:
    active: dev
  redis:
    host: 106.54.127.4
    password: 123456
    timeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: "*"